services:
  - type: web
    name: training-backend
    env: node
    region: Frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
